//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int? SNumber { get; set; }
        public System.Guid CompanyId { get; set; }
        public Nullable<int> BundleNumber { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
